<?php

namespace AppBundle\Repository;

/**
 * BookAndAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookAndAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
